name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Creating and activating virtualenv
        run: |
          python3 -m pip install virtualenv
          python3 -m virtualenv venv
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          pip install dvc[gdrive]
          ls -la
          pip install -r tests/requirements_test.txt
      - name: Test API
        run: |
          dvc pull model/model.pkl -r model-track --force
          pytest tests
